# Generated by Django 5.2.3 on 2025-08-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='log_type',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='volume_ml',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='calories_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='carbs_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='fat_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='protein_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='objective',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('local_video_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.musclegroup')),
            ],
        ),
    ]
